name: med_app
description: "A new Flutter project."
version: 1.0.0+1
publish_to: none
environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  shared_preferences: ^2.3.2
  provider: ^6.1.2
  pdf: ^3.10.7
  printing: ^5.13.1
  image_picker: ^1.0.7
  path_provider: ^2.1.3
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  cloud_firestore: ^6.1.0
  
  # Local packages
  # pediatric_dose_calculator:
    # path: packages/pediatric_dose_calculator
    
  pediatric_dose_calculator:
    git:
      url: https://github.com/Amraaka/Med_app.git
      path: packages/pediatric_dose_calculator
      ref: main

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/fonts/NotoSans-Regular.ttf
    # Drug suggestions data
    - assets/data/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  fonts:
    - family: NotoSans
      fonts:
        - asset: assets/fonts/NotoSans-Regular.ttf
          weight: 400
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 400
